version: '3.2'

services:

  mysql:
    container_name: mysql
    image: mysql:8
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=1234567890
      - MYSQL_DATABASE=funcional
      - MYSQL_USER=funcional
      - MYSQL_PASSWORD=123456
    ports:
      - 3306:3306
    network_mode: "bridge"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:db
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 81:80
    network_mode: "bridge"

  app:
    container_name: app
    image: jgcl88/laravel-graphql
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - TZ=America/Sao_Paulo
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=funcional
      - DB_USERNAME=funcional
      - DB_PASSWORD=123456
      - CACHE_DRIVER=database
    links:
      - mysql:db
      - redis:redis
    ports:
      - 80:80
    network_mode: "bridge"

volumes:
  mysql:
    driver: "local"
